# -*- coding: utf-8 -*-
"""CV-CO1-AT1-Q02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Njbm1kcq0WFPACyjB1QhrSEk9fEQW8nN
"""

from google.colab import files
from PIL import Image
import matplotlib.pyplot as plt
import cv2
import numpy as np

# Upload image
uploaded = files.upload()

# Read uploaded image
filename = list(uploaded.keys())[0]
img = Image.open(filename)

# Convert to OpenCV format
img_cv = cv2.cvtColor(np.array(img), cv2.COLOR_RGB2BGR)

# Brightness enhancement
enhanced = cv2.convertScaleAbs(img_cv, alpha=2.0, beta=40)

# Display images
plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.imshow(cv2.cvtColor(img_cv, cv2.COLOR_BGR2RGB))
plt.title("Original Low-Light Image")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(cv2.cvtColor(enhanced, cv2.COLOR_BGR2RGB))
plt.title("Enhanced Image (After Acquisition & Processing)")
plt.axis("off")

plt.tight_layout()
plt.show()
